services:
  app-1:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-1
    user: "www-data:www-data"
    image: base-1
    volumes:
      - ./:/var/www
    ports:
      - "8001:8001"
    networks:
      - shared-net

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - shared-net

  nginx-1:
    image: nginx:alpine
    container_name: nginx-1
    ports:
      - "8081:8081"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - shared-net

networks:
  shared-net:
    external: true
